#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "tag required in first argument, e.g. `./deploy v2.0.1`"
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
ssh pva@portlandvolleyball.org "eval '$(ssh-agent -s /bin/sh)';echo 'here';ssh-add /home/pva/.ssh/joshuabremer_id_rsa;cd portlandvolleyball.org; git fetch josh; echo $1";

