<?php include("header.html"); ?>

<h1>Rule Differences</h1>
<p><i>NFSHA MODIFICATIONS TO USA RULES<br>
(updated 01/01/2001)</i></p>

<table class="interiorTable">
  <tr>
    <th>ITEM</th>
    <th>USA</th>
    <th>PARK BUREAU</th>
    <th>FEDERATION</th>
  </tr>

  <tr>
    <td><b>BLOCK/SPIKE OF SERVE</b></td>
    <td>CANNOT BLOCK OR ATTACK A SERVED BALL ABOVE THE HEIGHT OF THE NET</td>
    <td>CANNOT BLOCK OR ATTACK A SERVED BALL ABOVE THE HEIGHT OF THE NET</td>
    <td>LEGAL</td>
  </tr>
  <tr>

    <td><b>CEILING HEIGHT</b></td>
    <td>ALL BALLS LIVE</td>
    <td>ALL BALLS LIVE</td>
    <td>ALL BALLS LIVE</td>
  </tr>
  <tr>
    <td><b>TIMEOUTS</b></td>

    <td>ONLY 2</td>
    <td>ONLY 2</td>
    <td>3RD, AS TEAMS REACH 14-14</td>
  </tr>
  <tr>
    <td><b>BACKROW BLOCKING</b></td>
    <td>LEGAL,IF BALL NOT TOUCHED</td>

    <td>LEGAL, IF BALL NOT TOUCHED</td>
    <td>ILLEGAL ACTION</td>
  </tr>
  <tr>
    <td><b>COIN TOSS</b></td>
    <td>OPPOSITE TEAM CALLS LAST GAME</td>
    <td>HOME TEAM CALLS ALL TOSSES, IF HOME TEAM HAS NO SCOREBOARD, VISITORS WIN ALL TOSSES</td>

    <td>VISITING TEAM CALLS ALL TOSSES</td>
  </tr>
  <tr>
    <td><b>CENTERLINE CROSSING</b></td>
    <td>LEGAL OUTSIDE OF SIDELINE BOTH THE FOOT AND PALM CAN BE ON OR ABOVE THE
CENTER LINE</td>
    <td>LEGAL OUTSIDE OF SIDELINE BOTH THE FOOT AND PALM CAN BE ON OR ABOVE THE CENTER LINE.</td>
    <td>ILLEGAL EVEN IF OUTSIDE SIDELINE</td>

  </tr>
  <tr>
    <td><b>MULTIPLE CONTACTS</b></td>
    <td>LEGAL ON FIRST BALL, INCLUDING SERVE, AS LONG AS ONE ATTEMPT. FINGER ACTION IS ALLOWED.</td>
    <td>LEGAL ON HARD-DRIVEN 1ST BALL, INCLUDING SERVE, AS LONG AS ONE ATTEMPT.  FINGER ACTION IS ALLOWED.</td>
    <td>LEGAL IF RECEIVING HARD DRIVEN SPIKE OR BLOCKING NO FINGERS, ONE ATTEMPT.</td>
  </tr>

  <tr>
    <td><b>CONTACT WITH OPPONENT</b></td>
    <td>LEGAL UNLESS INTENTIONAL</td>
    <td>LEGAL UNLESS INTENTIONAL</td>
    <td>ILLEGAL IF IT INTERFERES WITH PLAY OR INTENTIONAL</td>
  </tr>
  <tr>

    <td><b>JEWELRY</b></td>
    <td>ALL JEWELRY ILLEGAL</td>
    <td>NONE WHICH COULD CAUSE INJURY, OFFICIALS JUDGEMENT</td>
    <td>ALL JEWELRY ILLEGAL</td>
  </tr>
  <tr>
    <td><b>SUBSTITUTIONS</b></td>

    <td>12 TEAM SUB-RULE-3 ENTRIES</td>
    <td>12 TEAM SUB-RULE-3 ENTRIES</td>
    <td>3 ENTRIES-TEAM UNLIMITED</td>
  </tr>
  <tr>
    <td><b>ILLEGAL SUBSTITUTION</b></td>
    <td>CHARGED TEAM DELAY IF PLAY AFFECTED</td>

    <td>CHARGED TEAM DELAY IF PLAY AFFECTED</td>
    <td>UNNECESSARY DELAY - TIME OUT CHARGED</td>
  </tr>
  <tr>
    <td><b>INADVERTENT CONTACT WITH STANDARDS</b></td>
    <td>LEGAL</td>
    <td>LEGAL</td>

    <td>LEGAL UNLESS DANGEROUS, NO CABLE CONTACT</td>
  </tr>
  <tr>
    <td><b>INJURY</b></td>
    <td>STOP PLAY-REPLAY DIRECTED PLAYER HAS 15 SECONDS TO PLAY ONE TIME OUT CHARGED IF PLAYER IS TO REMAIN IN GAME.  IF RE-MOVAL CAUSES DELAY, NO TIME OUT CHARGED</td>
    <td>STOP PLAY-REPLAY DIRECTED PLAYER HAS 15 SEC. TO PLAY ONE TIME OUT CHARGED  IF PLAYER IS TO REMAIN IN GAME.  IF REMOVAL CAUSES DELAY, NO TIMEOUT CHARGED</td>
    <td>STOP PLAY-REPLAY DIRECTED NO TIME OUT CHARGED IF PLAYER LEAVES GAME.  IF PLAYER STAYS IN GAME AND IS NOT READY TO PLAY IN 30 SECONDS FROM STOPPED PLAY - TEAM CHARGED TIME OUT AND 60 SECONDS GIVEN IF TEAM HAS LEGAL TIME OUT
    </td>

  </tr>
  <tr>
    <td><b>MATCH</b></td>
    <td>BEST TWO OF THREE OR THREE OF FIVE</td>
    <td>ALWAYS PLAY ALL THREE GAMES</td>
    <td>PLAY THIRD, IF REQUIRED FOR MATCH.</td>
  </tr>

  <tr>
    <td><b>BALL</b></td>
    <td>APPROVED BY USA WITH SPEC</td>
    <td>OFFICIAL DETERMINES GAME BALL. TEAMS PROVIDE</td>
    <td>ANY BALL WHICH MEETS FEDERATION SPECIFICATIONS</td>
  </tr>
  <tr>

    <td><b>SCOREBOARD</b></td>
    <td>SCORE BOOK OFFICIAL</td>
    <td>HOME TEAM PROVIDES</td>
    <td>IS OFFICIAL  SCOREBOOK OFFICIAL</td>
  </tr>
  <tr>
    <td><b>NUMBERS</b></td>

    <td>NOT LESS THAN 6" ON BACK AND 3" ON FRONT</td>
    <td>FRONT ONLY (OR USA) 1-99 NO OO'S; NOT REQUIRED</td>
    <td>NOT LESS THAN 3/4" WIDTH BACK 6", FRONT 4"</td>
  </tr>
  <tr>
    <td><b>OFFICIAL'S UNIFORM</b></td>
    <td>WHITE SHIRT, BLUE PANTS</td>

    <td>WHITE SHIRT, BLACK PANTS</td>
    <td>WHITE SHIRT, BLACK PANTS</td>
  </tr>
  <tr>
    <td><b>NUMBER OF PLAYERS</b></td>
    <td>MUST ALWAYS HAVE 6 ON COURT</td>
    <td>MAY PLAY WITH 5 IF COED, 3 WOMEN, 2 MEN</td>

    <td>MUST START WITH 6, CAN PLAY WITH 5</td>
  </tr>
  <tr>
    <td><b>TALK TO OFFICIAL</b></td>
    <td>CAPTAIN ONLY</td>
    <td>TEAM CAPTAIN</td>
    <td>CAPTAIN OR COACH</td>

  </tr>
  <tr>
    <td><b>SERVE</b></td>
    <td>CLEARLY VISIBLE-BALL TOSSED OR RELEASED</td>
    <td>CLEARLY VISIBLE-BALL TOSSED OR RELEASED</td>
    <td>HELD OR TOSSED OR DROPPED</td>
  </tr>

  <tr>
    <td><b>BALL MOTIONLESS OVERHEAD</b></td>
    <td>DEAD BALL</td>
    <td>AWARDED TO TEAM ON OPPOSITE SIDE BALL LANDS</td>
    <td>REPLAY, UNLESS 3RD HIT</td>
  </tr>
  <tr>

    <td><b>PROTESTS</b></td>
    <td>ALLOWABLE IF BEFORE NEXT SERVE</td>
    <td>ALLOWABLE IF BEFORE NEXT SERVE</td>
    <td>NOT ALLOWED</td>
  </tr>
  <tr>
    <td><b>PRE-GAME CONFERENCE</b></td>

    <td>CAPTAINS</td>
    <td>CAPTAINS</td>
    <td>COACH AND CAPTAIN</td>
  </tr>
  <tr>
    <td><b>SHOES</b></td>
    <td>PLIABLE SHOES</td>

    <td>NO BARE FEET, EXCEPT OUTDOORS</td>
    <td>NO BARE FEET</td>
  </tr>
  <tr>
    <td><b>OFFICIAL'S AUTHORITY</b></td>
    <td>AFTER COIN TOSS</td>
    <td>ENTERS GAME AREA</td>

    <td>ENTERS GAME AREA</td>
  </tr>
  <tr>
    <td><b>SERVICE AREA</b></td>
    <td>ENTIRE BACK LINE</td>
    <td>ENTIRE BACK LINE</td>
    <td>ENTIRE BACK LINE</td>

  </tr>
  <tr>
    <td><b>NET TOUCHES</b></td>
    <td>INADVERTENT TOUCHES OK</td>
    <td>INADVERTENT TOUCHES OK</td>
    <td>INADVERTENT TOUCHES OK</td>
  </tr>

  <tr>
    <td><b>SERVE RECEIVE</b></td>
    <td>SET ATTEMPTS ARE LEGAL, PROVIDING THE BALL DOESN'T COME TO REST</td>
    <td>SET ATTEMPTS ARE LEGAL, PROVIDING THE BALL DOESN'T COME TO REST</td>
    <td>SET ATTEMPTS ARE LEGAL, PROVIDING THE BALL DOESN'T COME TO REST</td>
  </tr>
  <tr>

    <td><b>LET SERVE</b></td>
    <td>SERVE IS LEGAL IF IT HITS THE NET AND GOES OVER</td>
    <td>SERVE IS LEGAL IF IT HITS THE NET AND GOES OVER</td>
    <td>SERVE IS LEGAL IF IT HITS THE NET AND GOES OVER</td>
  </tr>
  <tr>
    <td><b>DEFENSIVE SPECIALIST<br>(LE BERO)</b></td>

    <td>LEGAL IN THE BACK ROW.  COED TEAMS MUST STILL OBEY COED RULES.  TEAM CAN ONLY USE ONE PLAYER PER MATCH AS LE BERO.</td>
    <td>LEGAL IN THE BACK ROW. COED TEAMS MUST STILL OBEY COED RULES. TEAM CAN ONLY USE ONE PLAYER PER MATCH AS LE BERO.</td>
    <td>LEGAL IN THE BACK ROW. COED TEAMS MUST STILL OBEY COED RULES. TEAM CAN ONLY USE ONE PLAYER PER MATCH AS LE BERO.</td>


  </tr>
</table>

<?php include("footer.html"); ?>